select * from empy;
select distinct job from empy;
select ename,sal from empy order by sal;
select * from empy order by deptno,job desc;
select distinct job from empy order by job;
Select * from empy where empno in ( select mgr from empy) ;
select * from empy where hiredate<'1981-01-01';
select empno,ename,sal,sal/30 as daily_sal,sal*12 as annsal from empy order by annsal;
select empno,ename ,job,hiredate, format((datediff(current_date,hiredate))/365,0) exp_year from empy where job='manager';
select empno,ename,sal,format((datediff(current_date,hiredate))/365,0) exp_year from empy where mgr=7369;
select * from empy where comm>sal;
select ename,job,hiredate from empy where hiredate>'1981-06-01' order by hiredate;
select ename,format((datediff(current_date,hiredate))/365,0) exp_year,sal/30 daily_sal from empy where (sal/30)>100; 
select ename,job from empy where job='clerk' or job='analyst' order by job desc;
select ename,hiredate from empy where hiredate in('1981-05-01','1981-12-03','1981-12-17','1980-01-19');
select ename,deptno from empy where deptno=10 or deptno=20;
select ename,hiredate from empy where year(hiredate) in (1981);
select ename,hiredate from empy where month(hiredate) in(08) and year(hiredate) in (1980);
select ename,sal*12 annalsal from empy where (sal*12) between 22000 and 45000;
select ename from empy where ename like '_____';
select ename from empy where ename like 's____';
select ename from empy where ename like '__r_';
select ename from empy where ename like 's___h';
select ename,monthname(hiredate) from empy where monthname(hiredate) like 'January';
select ename,monthname(hiredate) from empy where monthname(hiredate) like '_a%';
select ename,sal from empy where sal like '___0';
select ename from empy where ename like '%ll%';
select ename,year(hiredate) from empy where year(hiredate) like '198_';
select ename,deptno from empy where deptno not in (20);
select * from empy where job!='president' and job<>'manager' order by sal;
select * from empy where year(hiredate)<1981 or year(hiredate)>1981;
select * from empy where empno not like '78%';
select e.ename,m.ename manager from empy e,empy m where e.mgr=m.empno; 
select * from empy where monthname(hiredate) not like 'March';
select * from empy where job like 'clerk' and deptno=20;
select * from empy where deptno in(30,10) and year(hiredate) like '1981';
select * from empy where ename='smith';
select ename,loc from empy e,dept d where e.ename='smith' and d.deptno=e.deptno;
select * from empy e,dept d where d.deptno=e.deptno and d.dname in('accounting','research');
select empno,ename,sal,dname from empy e,dept d where job in('manager','analyst') and loc='new york' and (format(datediff(current_date,hiredate),0))>7 and comm is null order by loc;
select empno,ename,sal,dname,loc,d.deptno,job from empy e,dept d where (d.loc='chicago' or d.dname='accounting') and d.deptno=e.deptno and e.empno in(select e.empno from empy e where (sal*12)>28000 and e.sal not in(3000,2800) and e.job!='mgr' and (e.empno like '__7%' or e.empno like '__8%')) order by e.deptno asc,e.deptno desc;
select * from empy order by grade;
select * from empy where grade in(2,3);
select * from empy where grade in(4,5) and job in('analyst','manager') ;
select e.empno,e.ename,e.sal,d.dname,e.grade,format(datediff(current_date,e.hiredate),0) as exp,(e.sal*12) as annal_sal from empy e,dept d where e.deptno in(10,20) and e.deptno=d.deptno;
with emp_dept as(select empno,ename,job,mgr,hiredate,sal,grade,d.dname,e.deptno,loc from empy e,dept d where e.deptno=d.deptno) select * from emp_dept where (grade between 2 and 4) and ((dname not like 'op%')and(dname not like '%s')) and (job like '%a%') and ((year(hiredate)=1981) and (monthname(hiredate)not in ('march','september'))) and (sal not like '%00') order by grade;
select d.deptno,d.dname,e.empno from empy e,dept d  where e.deptno=d.deptno;
select * from empy where sal>(select sal from empy where ename='blake');
select * from empy where job like(select job from empy where ename='allen');
select * from empy where hiredate<(select hiredate from empy where ename='king');
select * from empy e,empy w where e.empno=w.mgr and w.hiredate<e.hiredate;
create view dept_20 as select * from empy where deptno=20 ; create view dept_10 as select * from empy where deptno=10; select * from dept_20 d1,dept_10 d2 where d1.job=d2.job;
select * from empy where sal in(select sal from empy where (ename='ford' or ename='smith')) order by sal desc;
select * from empy where job in(select job from empy where (ename='miller')) or (sal>(select sal from empy where ename='allen'));  
select * from empy where sal>(select sum(sal+comm) from empy where job='salesman');
select * from empy e,dept d where hiredate>(select hiredate from empy where ename='blake' and e.deptno=d.deptno) and (d.loc in('chicago','boston'));
create view acc_res as select empno,ename,job,mgr,hiredate,sal,comm,grade,e.deptno,dname,loc from empy e,dept d where e.deptno in (select d.deptno from dept d where (grade in(3,4) )and d.dname in('accounting','research')); select * from acc_res where (sal>(select sal from empy where ename='allen')) and (hiredate>(select hiredate from empy where ename='smith')) order by hiredate ;
select * from empy where job in(select job from empy where ename='allen' or ename='smith');
select * from empy e where e.deptno = 10 and e.job not in (select job from empy where deptno =20);
select * from empy emp1  join empy emp2 on emp1.empno=emp2.empno;
select max(sal) from empy; select sal from (select sal,row_number() over(order by sal desc)as a from empy)b where a=1;
select * from empy where sal=(select max(sal) from empy);
select empno,ename,sal,job,dname,loc from (select empno,ename,job,sal,hiredate,grade,mgr,comm,e.deptno,dname,loc,row_number() over(partition by d.dname order by sal desc)as rn from empy e,dept d where d.deptno=e.deptno)as sales where rn=1 and dname='sales';
create view hired as select empno,ename,job,sal,hiredate,grade,mgr,comm,e.deptno,dname,loc from empy e,dept d where e.deptno=d.deptno and grade=3; select * from (select *,row_number() over(order by hiredate)as d from hired) b where d=1;
select * from empy where hiredate <(select max(hiredate) from empy where  mgr in (select empno from empy where ename='king'));
with emp_dept as(select empno,ename,job,mgr,hiredate,sal,grade,d.dname,e.deptno,loc from empy e,dept d where e.deptno=d.deptno) select * from emp_dept where loc=('new york') and (grade between 3 and 5) and (job !='president');
select * from empy where hiredate=(select min(hiredate) from empy where year(hiredate) like '1981');
select * from empy where hiredate=(select min(hiredate) from empy where year(hiredate) like '1981');
select * from empy where mgr=(select empno from empy where ename='king' and grade>3 and hiredate=(select min(hiredate) from empy));
select job,sum(sal) as total from empy where job='manager';
select job,sum(12*sal)as annal from empy where year(hiredate) like '1981' group by job;
select grade,sum(sal)as total from empy where grade=3;
select job,avg(sal)as avg from empy where job='clerk';
select *,avg(sal) from empy where deptno=20 and sal>(select avg(sal) from empy where deptno=10);
select e.job,count(e.empno) as employees,d.deptno from empy e,dept d where e.deptno=d.deptno group by d.deptno order by d.deptno;
select ename as manager,count(mgr) as employees from empy where mgr in(select empno from empy) group by mgr order by count(mgr);
select d.deptno,count(*) as emp from empy e,dept d  group by d.dname having count(*)>=2;
select grade,count(empno) as employees,max(sal) from empy group by grade order by grade;
select d.dname,e.grade,count(e.empno)as emps from empy e,dept d where job='clerk' group by e.empno having count('clerk')>=2;
select * from dept where deptno in(select deptno from empy group by deptno having count(*) in (select count(empno) from empy group by deptno) );
select * from empy where mgr in(select empno from empy where ename='jones');
select * from empy where (sal+((20/sal)*100)>3000); 
select e.ename,d.dname from empy e,dept d where e.deptno=d.deptno;
select * from empy e,dept d where e.deptno=d.deptno and d.dname not like 'sales';
select e.ename,d.deptno,e.sal,e.comm from empy e,dept d where e.deptno=d.deptno and e.sal between 2000 and 5000 and d.loc like'chicago';
select * from empy e,empy e1 where e.mgr in (select e1.empno from empy where e.sal>e1.sal);
select grade,ename from empy where deptno=10 or 30 and grade!=4 and hiredate>'1982-12-31';
select e.ename,e.job,d.dname,d.loc from empy e,dept d where e.job='manager';
select * from empy where mgr in(select empno from empy where ename='jones');
select ename,sal from empy where grade in(select grade from empy where sal>(select sal from empy  where ename='ford'));
select e.ename,e.job,d.dname,e.sal,e.grade from empy e,dept d where e.deptno=d.deptno order by d.dname;
select e.ename,e.job,e.sal,e.grade,d.dname from empy e,dept d where e.deptno=d.deptno and e.job!='clerk' order by e.sal;
select ename,job from empy where mgr not in(select empno from empy where job!='manager');
select ename,max(sal),deptno from empy group by deptno;
select ename,sal from empy where sal=(select (min(sal)+max(sal)/2) from empy);
with depts as (select count(*) as emps,deptno from empy group by deptno) select emps from depts where emps>3;
with depts as (select count(*) as emps,e.deptno,d.dname from empy e,dept d  where e.deptno=d.deptno group by e.deptno) select * from depts where emps>3;
with sals as(select e.ename,e.sal,e1.ename as mgr,e1.sal as mgrsal from empy e,empy e1 where e.mgr in(select e1.empno from empy)) select * from(select mgr,avg(sal) as empavg,mgrsal from sals where mgr in(select mgr from sals) group by mgr)as a where empavg<mgrsal;
with net as (select ename,sal,comm,(sal+comm) as netpay from empy) select ename,sal,comm from net where netpay>=any(select sal from net);
with sala as(select e.ename,e.sal,e1.ename as mgr,e1.sal as mgrsal from  empy e,empy e1 where e.mgr in(select e1.empno from empy where  e.sal>e1.sal)) select * from sala where sal>any(select mgrsal from sala) ;
select e.ename,avg(e.sal),d.dname from empy e,dept d where e.deptno=d.deptno group by d.dname;
select * from empy  order by sal  limit 5;
select * from empy e,empy e1 where e.mgr in(select e1.empno from empy where e.sal>e1.sal);
select * from empy where empno in(select mgr from empy) and mgr not in(select empno from empy where job = 'PRESIDENT');
select * from empy e,dept d where e.deptno!=d.deptno;
with nets as(select ename,sal,comm,(sal+comm)as netpay from empy) select * from nets where netpay>any(select sal from empy);
select ename from empy where adddate(hiredate,interval 20 year) > '1989-12-31';
select * from empy where sal%2=1;
select * from empy where sal like ('___');
select * from empy where monthname(hiredate)='december';
select * from empy where ename like ('%a%');
select * from empy where instr(sal,deptno);
select * from empy where substr(hiredate,1,2)=substr(sal,length(sal)-1,length(sal));
select * from empy where ((10/sal)*100)=date_format(hiredate,'%y');
select lcase(substr(ename,1,round((lenth(ename)/2)))||substr(ename,round(length(ename)/2))+1,lenth(ename)) from empy;
select d.dname,count(*) from empy e ,dept d where e.deptno=d.deptno group by d.dname having count(*) = length(d.dname);
select * from empy where date_format(hiredate,'%d')<'15';
with empys as(select d.dname,length(d.dname) as ldname,count(e.empno) as emp from empy e,dept d where e.deptno=d.deptno group by d.dname) select * from empys where ldname=emp;
select * from empy where job='manager';
with dnames as(select d.dname as dname,count(e.empno) as emp from empy e,dept d where e.deptno=d.deptno group by d.dname) select dname,max(emp) from dnames;
select count(*) from empy where job='manager';
select * from empy where hiredate=all(select hiredate from empy);
select * from empy e,dept d where e.deptno=d.deptno and e.grade =( 0.1*(select e.deptno from empy where d.dname='sales'));
select d.dname from dept d, empy e where e.deptno = d.deptno group by d.dname having count(*) > (select avg(count(*)) from empy group by deptno);
with mgr as(select e.ename as mgr ,count(e1.ename) as emps from empy e,empy e1 where e.mgr in(select e1.empno from empy)group by e1.ename) select * from mgr where emps=(select max(emps) from mgr);
select ename,(sal+(15/sal)*100)/79.72 as sal$ from empy;
select concat(ename,job) as EMP_AND_JOB from empy;
select concat_ws('(',ename,lcase(job)) as “EMPLOYEE” from empy;

select empno,ename,date_format(hiredate,'%M %d %Y') from empy;
select empno,ename,sal,case when sal>1500 then 'just salary' when sal=1500 then 'on target' else 'Below 1500' end as Listing from empy;
select dayofweek(curdate()) from dual;
set service=datediff(curdate,hiredate);

select ename,hiredate,case when dayofmonth(hiredate)>15 then (date_sub((hiredate),interval 15 day)) else last_day(hiredate) end as salaryDate from empy;
select length(ename) from empy;
select * from empy where instr(sal,'.');
select * from empy where sal like('___')=deptno;
select distinct m.ename,m.sal from empy w,empy m where w.mgr =m.empno and w.sal>m.sal;
select * from empy where mgr in (select empno from empy where ename ='BLAKE');
select * from empy where empno in (select mgr from empy);
select w.ename,m.ename,(select ename from empy where m.mgr = empno) as  Jonesmanager from empy w,empy m where w.mgr = m.empno and m.ename = 'JONES';

select count(*) from empy where job='manager';
select avg(sal),avg(sal*12),job from empy group by job;
select ename,count(*) from empy group by empno;
select * from empy where sal<1000 order by sal;
select e.ename,e.job,e.sal*12 as annasal,e.deptno,d.dname,e.grade from empy e,dept d where e.deptno=d.deptno and (e.sal*12)=36000 and job!='clerk'; 
select job,hiredate from empy where hiredate between '1983-01-01' and '1983-06-01' and hiredate between'1984-01-01' and '1984-06-01';
select e.ename,e.hiredate,e1.hiredate from empy e,empy e1 where e.mgr in(select e1.empno from empy where e.hiredate<e1.hiredate);
select e.ename,e.empno,e1.ename,e1.empno from empy e,empy e1 where e.mgr=e1.empno; 
select ename,job,min(sal) from empy group by job order by sal;
select ename,job,max(sal) from empy group by job order by sal desc;
select * from empy where hiredate in(select max(hiredate) from empy)order by hiredate;
with sals as (select ename,sal,deptno,avg(sal)as avg from empy group by deptno order by deptno)select * from sals where sal>avg;
select deptno from empy where empno=null;
select count(ename),avg(sal) from empy group by job order by deptno;
select max(sal),job from empy where job!='president' group by job;
select ename,job from empy where sal =(select max(sal) from empy);
select ename,job,sal from empy where deptno!=10 and sal in(select sal from empy )and job in(select job from empy);
select deptno,ename,job,sal,(sal+comm) from empy where job='salesman' order by comm;
with earn as (select deptno,ename,job,sal,(sal+comm) as earning from empy) select * from(select *,row_number()over(order by earning desc)as ea from earn)as e where ea=2;
select deptno,avg(sal) from empy group by deptno having avg(sal)<(select avg(sal) from empy);
select e.ename,e.empno,e.sal,e1.ename,e1.empno,e1.sal from empy e,empy e1 where e.mgr=e1.empno and e.sal>any(select e1.sal from empy); 
with high as(select ename,job,sal,avg(sal) as av,deptno from empy group by deptno order by deptno) select *,max(av) from high;
select empno,sal,comm from empy;
select * from empy order by sal;
select empno,ename,deptno from empy order by job,empno;
select distinct deptno from empy;
select distinct deptno,job from empy;
select * from empy where ename='blake';
select * from empy where job='clerk';
select * from empy where hiredate='1981-05-01';
select empno,ename,sal,deptno from empy where deptno=10 order by sal;
select * from empy where sal<3500;
select empno,ename,sal,hiredate from empy where hiredate<'1981-04-01';
with ann as (select *,(sal*12) as annal from empy) select * from ann where annal<25000 order by sal;
with ann as (select empno,ename,(sal*12)as annal,(sal/30)as daily from empy where job='salesman') select * from ann order by annal;
with exp as (select empno,ename,hiredate,curdate(),format(datediff(current_date,hiredate)/365.0,0) as ep from empy) select * from exp order by ep;
with exp as (select empno,ename,hiredate,curdate(),format(datediff(current_date,hiredate)/365.0,0) as ep from empy) select * from exp where ep>10;
with emp as(select empno,ename,sal,(30/sal)*100 as DA,(40/sal)*100 as HRA,(50/sal)*100 as GROSS,(sal+comm)as net from empy)select * from emp order by net;
select * from empy where job='manager';
select * from empy where job='clerk' or 'manager';
select * from empy where hiredate in('1981-05-01','1981-11-17','1981-12-30');
select * from empy where year(hiredate) like '1981';
select * from empy where (12* sal) between 23000 and 40000;
select * from empy where mgr in(7369,7890,7654,7900);
select * from empy where hiredate between '1982-06-01' and '1982-12-30';
select * from empy where length(ename)=4;
select * from empy where ename like 's____';
select * from empy where ename like '____h';
select * from empy where ename like 'M%';
select * from empy where year(hiredate)=1981;
select * from empy where sal like '%00';
select * from empy where monthname(hiredate)='january';
select * from empy where monthname(hiredate) like '%a%';
select * from empy where monthname(hiredate) like '_a%';
select * from empy where length(sal)=4;
select * from empy where year(hiredate)=1980;
select * from empy where job='clerk' and (datediff(current_date,hiredate)/365)>8;
select * from empy where deptno in(10,20) and job='manager';
select * from empy where monthname(hiredate)='january' and sal between 1500 and 4000;
select distinct job,deptno from empy where deptno in(20,30) order by deptno;
select ename,format((datediff(current_date,hiredate)/365),0) as exp from empy where (mgr like '7%' and mgr not like '%9%') and year(hiredate)=1983;
select * from empy where (job in ('manager' ,'analyst') ) and sal between 2000 and 5000 and comm is null;
select empno,ename,sal,job from empy where (sal*12)<34000 and comm>sal and job='salesman' and deptno=30;
select * from empy where (deptno in(10,20)) and (job in('clerk','analyst')) and (length(sal) in(3,4)) and ((datediff(current_date,hiredate)/365)>8) and (monthname(hiredate) not in('march','april','september')) and empno in(select mgr from empy) and empno not like '%88' and empno not like '%56';
select empno,ename,sal,job,deptno,format((datediff(current_date,hiredate)/365),0) as exp from empy where (deptno in(10,20)) and ((datediff(current_date,hiredate)/365) in(6,10)) and (mgr in(select empno from empy)) and (comm is null);
select * from empy e,dept d where e.deptno=d.deptno and d.loc='chicago';
select e.empno,e.ename,d.deptno,d.loc from empy e,dept d where e.deptno=d.deptno;
select empno,ename,d.loc,d.dname,e.deptno from empy e,dept d where e.deptno=d.deptno and e.deptno in(10,20);
select empno,ename,sal,loc from empy e,dept d where e.deptno=d.deptno and loc='chicago' and format((datediff(current_date,hiredate)/365),0)>6;
select * from empy e,dept d where e.deptno=d.deptno and loc in('dallas','newyork') and sal between 2000 and 5000 and year(hiredate)=1981;
select empno,ename,sal,grade from empy;
select * from empy where grade in(2,3);
select * from empy e,dept d where e.deptno=d.deptno and (d.dname='accounting' or (loc='dallas' or loc='chicago')) and grade between 3 and 5 and  format((datediff(current_date,hiredate)/365),0)>6;
select * from empy e,dept d where grade=3 and d.dname in('research','operations') and year(hiredate) >1987 and (ename!='miller' or ename!='allen');
select * from empy where job in(select job from empy where ename='smith');
select * from empy where hiredate <(select hiredate from empy where ename='miller');
select * from empy where (job in(select job from empy where ename='allen')) or (sal>(select sal from empy where ename='allen'));
select * from empy e,empy e1 where e.empno in(select e1.mgr from empy where e.hiredate>e1.hiredate);
select * from empy where sal>(select sal from empy where ename='blake');
select * from empy where deptno=10 and sal>(select sal from empy where ename='allen');
select * from empy where empno in(select mgr from empy where hiredate<(select hiredate from empy where ename='king')) and hiredate>(select hiredate from empy where ename='smith');
select empno,ename,loc,sal,d.dname from empy e,dept d where  e.deptno=d.deptno and e.deptno=(select deptno from empy where ename='king'); 
select * from empy where grade<(select grade from empy where ename='miller');
select * from empy e,dept d where e.deptno=d.deptno and (d.loc in('dallas','chicago')) and (e.grade in(select grade from empy where ename='adams')) or (e.hiredate>(select hiredate from empy where ename='smith'));
select * from empy where sal in(select sal from empy where ename='ford' or ename='blake');
select * from empy e where sal in(select sal from empy where e.empno=empno);
select * from empy where sal in(select sal from empy where job='clerk');
select * from empy where year(hiredate)<1982;
select ename,(sal+comm)as remuneration from empy e,dept d where job='salesman' and d.dname='sales';
select ename,sal from empy where grade=4; 
select ename,sal from empy;
select * from empy where sal in(select max(sal) from empy);
select * from empy where hiredate in(select max(hiredate) from empy where deptno=30);
select * from empy e,dept d where hiredate in(select max(hiredate) from empy where d.loc='chicago' and grade=2);
select * from empy where hiredate in(select max(hiredate) from empy where mgr in(select empno from empy where ename='king'));